-- MySQL Script generated by MySQL Workbench
-- Sun Aug 13 19:49:32 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema devicecloud_schema
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `devicecloud_schema` ;

-- -----------------------------------------------------
-- Schema devicecloud_schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `devicecloud_schema` ;
USE `devicecloud_schema` ;

-- -----------------------------------------------------
-- Table `devicecloud_schema`.`device_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devicecloud_schema`.`device_types` ;

CREATE TABLE IF NOT EXISTS `devicecloud_schema`.`device_types` (
  `iddevice_type` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `device_type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iddevice_type`),
  UNIQUE INDEX `device_type_name_UNIQUE` (`device_type_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `devicecloud_schema`.`devices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devicecloud_schema`.`devices` ;

CREATE TABLE IF NOT EXISTS `devicecloud_schema`.`devices` (
  `iddevices` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `device_type_iddevice_type` INT UNSIGNED NOT NULL,
  `device_id` CHAR(35) NOT NULL,
  `device_mac` CHAR(13) NOT NULL,
  `IP_Address` INT UNSIGNED NOT NULL,
  `Global_Address` INT UNSIGNED NOT NULL,
  `Description` VARCHAR(45) NULL DEFAULT NULL,
  `Contact` VARCHAR(45) NULL DEFAULT NULL,
  `Location` VARCHAR(45) NULL DEFAULT NULL,
  `customer_id` VARCHAR(45) NULL,
  PRIMARY KEY (`iddevices`),
  UNIQUE INDEX `device_mac_UNIQUE` (`device_mac` ASC),
  UNIQUE INDEX `device_id_UNIQUE` (`device_id` ASC),
  INDEX `fk_devices_device_type_idx` (`device_type_iddevice_type` ASC),
  CONSTRAINT `fk_devices_device_type`
    FOREIGN KEY (`device_type_iddevice_type`)
    REFERENCES `devicecloud_schema`.`device_types` (`iddevice_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `devicecloud_schema`.`streams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devicecloud_schema`.`streams` ;

CREATE TABLE IF NOT EXISTS `devicecloud_schema`.`streams` (
  `idstreams` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `streams_id` VARCHAR(100) NOT NULL,
  `devices_iddevices` INT UNSIGNED NOT NULL,
  `data_types` ENUM('INTEGER', 'LONG', 'FLOAT', 'DOUBLE', 'STRING', 'BINARY', 'UNKNOWN', 'JSON') NOT NULL,
  `description` VARCHAR(45) NULL,
  `data_ttl` INT NULL DEFAULT 8035200,
  `rollup_ttl` INT NULL DEFAULT 63244800,
  `units` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idstreams`),
  UNIQUE INDEX `streams_id_UNIQUE` (`streams_id` ASC),
  INDEX `fk_streams_devices1_idx` (`devices_iddevices` ASC),
  CONSTRAINT `fk_streams_devices1`
    FOREIGN KEY (`devices_iddevices`)
    REFERENCES `devicecloud_schema`.`devices` (`iddevices`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `devicecloud_schema`.`data_points`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devicecloud_schema`.`data_points` ;

CREATE TABLE IF NOT EXISTS `devicecloud_schema`.`data_points` (
  `iddata_points` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `streams_idstreams` INT UNSIGNED NOT NULL,
  `data` VARCHAR(100) NOT NULL,
  `description` VARCHAR(45) NULL,
  `quality` INT NULL,
  `location` VARCHAR(45) NULL,
  `timestamp` TIMESTAMP(14) NOT NULL,
  `server_timestamp` TIMESTAMP(14) NOT NULL,
  PRIMARY KEY (`iddata_points`),
  INDEX `fk_data_points_streams1_idx` (`streams_idstreams` ASC),
  CONSTRAINT `fk_data_points_streams1`
    FOREIGN KEY (`streams_idstreams`)
    REFERENCES `devicecloud_schema`.`streams` (`idstreams`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
